version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html

  db:
    image: postgres:14
    env_file: .env
    environment:
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

